/**
 * `create-leak-config`
 *
 * Deploys the PLATFORM-OWNED Meteora DBC PoolConfig for Pool 1
 * (Leak / rfstacc, binding target = 10 000 rfstacc).
 *
 * This config is created once per protocol deployment and reused by all Leak
 * pool instances.  Only the platform keypair (generated by `generate-platform-key`)
 * needs to sign.
 *
 * On-chain config parameters baked in per the spec:
 *   - Quote mint       : r-fstacc LST  (pSYRpDqr847kB2nD5ZhjcPsHLV2ZpUxweXm1MwiSTcc)
 *   - Binding target   : 10 000 rfstacc (raw = 10 000 × 10^9)
 *   - Initial fee      : 99 % (anti-snipe), decaying to 1 % over ~200 s
 *   - Partner          : platform keypair pubkey
 */
import { Command } from "commander";
import { Connection, Keypair, PublicKey, Transaction, SystemProgram, sendAndConfirmTransaction, TransactionInstruction } from "@solana/web3.js";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import {
  METEORA_DBC_PROGRAM_ID,
  R_FSTACC_LST_MINT,
  POOL1_BINDING_TARGET_QUOTE_RAW,
  POOL1_INITIAL_FEE_BPS,
  POOL1_BASELINE_FEE_BPS,
  POOL1_FEE_DECAY_SLOTS,
} from "../../constants.js";

// Anchor discriminator for `create_config` (sha256("global:create_config")[0..8])
const CREATE_CONFIG_DISCRIMINATOR = Buffer.from([
  0x9b, 0x16, 0x44, 0x2e, 0xc8, 0x04, 0x1b, 0xf5,
]);

/** Serialise a u64 (bigint) into 8 little-endian bytes. */
function u64LE(value: bigint): Buffer {
  const buf = Buffer.alloc(8);
  buf.writeBigUInt64LE(value);
  return buf;
}

/** Serialise a u16 into 2 little-endian bytes. */
function u16LE(value: number): Buffer {
  const buf = Buffer.alloc(2);
  buf.writeUInt16LE(value);
  return buf;
}

/**
 * Build the `create_config` instruction for Meteora DBC.
 *
 * Config data layout (after discriminator):
 *   tradingFeeRate      : u64  (fee in bps × 100, e.g. 100 bps = 1 %)
 *   protocolFeePercent  : u64  (percent of trading fee going to protocol)
 *   bindingTarget       : u64  (quote reserve at graduation, raw units)
 *   initialFeeRate      : u16  (anti-snipe start fee in bps)
 *   baselineFeeRate     : u16  (fee after decay in bps)
 *   feeDecaySlots       : u64  (slots over which fee decays)
 *
 * Accounts:
 *   0  config      (Keypair, writable, signer)
 *   1  partner     (platform keypair, signer)
 *   2  quoteMint   (r-fstacc LST, readonly)
 *   3  systemProgram
 */
function buildCreateConfigInstruction(opts: {
  configKeypair: Keypair;
  partner: PublicKey;
  quoteMint: PublicKey;
  tradingFeeRateBps: number;
  protocolFeePercent: number;
  bindingTargetRaw: bigint;
  initialFeeBps: number;
  baselineFeeBps: number;
  feeDecaySlots: number;
}): TransactionInstruction {
  const data = Buffer.concat([
    CREATE_CONFIG_DISCRIMINATOR,
    u64LE(BigInt(opts.tradingFeeRateBps)),
    u64LE(BigInt(opts.protocolFeePercent)),
    u64LE(opts.bindingTargetRaw),
    u16LE(opts.initialFeeBps),
    u16LE(opts.baselineFeeBps),
    u64LE(BigInt(opts.feeDecaySlots)),
  ]);

  return new TransactionInstruction({
    programId: METEORA_DBC_PROGRAM_ID,
    keys: [
      { pubkey: opts.configKeypair.publicKey, isSigner: true,  isWritable: true  },
      { pubkey: opts.partner,                  isSigner: true,  isWritable: false },
      { pubkey: opts.quoteMint,                isSigner: false, isWritable: false },
      { pubkey: SystemProgram.programId,       isSigner: false, isWritable: false },
    ],
    data,
  });
}

export function registerCreateLeakConfigCommand(program: Command): void {
  program
    .command("create-leak-config")
    .description(
      "Deploy the platform-owned Meteora DBC PoolConfig for Pool 1 (Leak/rfstacc). " +
      "Run once; save the printed config address for use with create-pools."
    )
    .requiredOption("--keypair <path>", "Path to the platform keypair JSON (generated by generate-platform-key)")
    .option("--rpc <url>", "Solana RPC URL", process.env.SOLANA_RPC_URL ?? "https://api.mainnet-beta.solana.com")
    .option("--output <path>", "JSON file to write config address into", "./leak-config.json")
    .option("--trading-fee-bps <n>", "Trading fee in basis points", "100")
    .option("--protocol-fee-percent <n>", "Protocol fee % of trading fee", "20")
    .action(async (opts: {
      keypair: string;
      rpc: string;
      output: string;
      tradingFeeBps: string;
      protocolFeePercent: string;
    }) => {
      const connection = new Connection(opts.rpc, "confirmed");

      const rawKp = JSON.parse(await readFile(path.resolve(opts.keypair), "utf8"));
      const platformKp = Keypair.fromSecretKey(Uint8Array.from(rawKp));

      const configKp = Keypair.generate();

      console.log(`Platform pubkey : ${platformKp.publicKey.toBase58()}`);
      console.log(`Config pubkey   : ${configKp.publicKey.toBase58()}`);
      console.log(`Quote mint      : ${R_FSTACC_LST_MINT.toBase58()}`);
      console.log(`Binding target  : 10 000 rfstacc (${POOL1_BINDING_TARGET_QUOTE_RAW} raw)`);

      const ix = buildCreateConfigInstruction({
        configKeypair: configKp,
        partner: platformKp.publicKey,
        quoteMint: R_FSTACC_LST_MINT,
        tradingFeeRateBps: parseInt(opts.tradingFeeBps),
        protocolFeePercent: parseInt(opts.protocolFeePercent),
        bindingTargetRaw: POOL1_BINDING_TARGET_QUOTE_RAW,
        initialFeeBps: POOL1_INITIAL_FEE_BPS,
        baselineFeeBps: POOL1_BASELINE_FEE_BPS,
        feeDecaySlots: POOL1_FEE_DECAY_SLOTS,
      });

      const tx = new Transaction().add(ix);
      const sig = await sendAndConfirmTransaction(connection, tx, [platformKp, configKp], {
        commitment: "confirmed",
      });

      const result = {
        configAddress: configKp.publicKey.toBase58(),
        signature: sig,
        partner: platformKp.publicKey.toBase58(),
        quoteMint: R_FSTACC_LST_MINT.toBase58(),
        bindingTargetRaw: POOL1_BINDING_TARGET_QUOTE_RAW.toString(),
      };

      await writeFile(path.resolve(opts.output), JSON.stringify(result, null, 2));

      console.log("\nPool 1 config deployed!");
      console.log(`  Config address : ${configKp.publicKey.toBase58()}`);
      console.log(`  Tx signature   : ${sig}`);
      console.log(`  Saved to       : ${opts.output}`);
    });
}
